import "../globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import Header from "../partials/Header";
import type { Metadata } from "next";
import React from "react";
import Sidebar from "../partials/Sidebar";
import theme from "../../../theme/themeConfig";
import { yekan } from "../fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="fa">
    <body className={`${yekan.variable} px-4 antialiased`}>
      <ConfigProvider theme={{ ...theme }}>
        <AntdRegistry>
          <div className="flex flex-col my-4 gap-y-4 h-full">
            <Header />

            <div className="flex flex-row h-screen gap-x-2">
              <Sidebar />

              <div className="w-full">{children}</div>
            </div>
          </div>
        </AntdRegistry>
      </ConfigProvider>
    </body>
  </html>
);

export default RootLayout;
