import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import Header from "./partials/Header";
import type { Metadata } from "next";
import React from "react";
import Sidebar from "./partials/Sidebar";
import localFont from "next/font/local";
import theme from "../../theme/themeConfig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const yekan = localFont({
  variable: "--font-yekan",
  src: [
    {
      path: "../../public/fonts/YekanBakhFaNum-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-SemiBold.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-ExtraBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-Black.woff2",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakhFaNum-ExtraBlack.woff2",
      weight: "900",
      style: "normal",
    },
  ],
});

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="fa">
    <body className={`${yekan.variable} px-4`}>
      <ConfigProvider theme={{ ...theme }}>
        <AntdRegistry>
          <div className="flex flex-col my-4 gap-y-4 h-full">
            <Header />

            <div className="flex flex-row h-screen gap-x-2">
              <Sidebar />

              <div className="w-full">{children}</div>
            </div>
          </div>
        </AntdRegistry>
      </ConfigProvider>
    </body>
  </html>
);

export default RootLayout;
