import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import React from "react";
import theme from "../../theme/themeConfig";
import { yekan } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="fa">
    <body className={`${yekan.variable} antialiased`}>
      <ConfigProvider theme={{ ...theme }}>
        <AntdRegistry>
          <div className="flex flex-col gap-y-4 h-full">
            <div className="flex flex-row h-screen gap-x-2">
              <div className="w-full">{children}</div>
            </div>
          </div>
        </AntdRegistry>
      </ConfigProvider>
    </body>
  </html>
);

export default RootLayout;
